version: "3.3"
services:
  db:
    image: postgres:15
    environment:
      PGDATA: /var/lib/postgresql/data/university_cafeteria_menu/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "app"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
  backend:
    build:
      dockerfile: ./app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
