version: "3.3"
services:
  db:
    image: postgres:15
    environment:
      PGDATA: /var/lib/postgresql/data/university_cafeteria_menu/
    env_file:
      - .env
    ports:
      - "5432:5432"
  backend:
    build:
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
